# Generated by Django 5.1.2 on 2024-10-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_work_time_companymodel_end_work_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='city',
            field=models.CharField(default='Набережные челны', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companymodel',
            name='slogan',
            field=models.CharField(default='Мы любим животных также как и вы', max_length=100),
            preserve_default=False,
        ),
    ]
