# Generated by Django 5.1.2 on 2024-10-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_companymodel_city_companymodel_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='service',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
